### ISSUE TITLE
The Hello World tutorial skips instructions on git repo for perlbrew cookbook

### ISSUE THREAD

**Issue by heikkil** [dagolden/perl-chef#5]
The tutorial has instructions for cloning cookbooks for Hello World, Runit and Perl Chef, but does not comment where to find the cookbook for perlbrew.

**Comment by dagolden** [comment]
perlbrew and carton cookbooks are contained in the Perl Chef repository.  The actual commands are correct and pull the cookbooks out of there, but I see that the text is not clear.  I'll revise it and see if I can replace the original on slideshare.

Thank you for letting me know about it.
